package com.weipan.smk1.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.weipan.smk1.bean.GvBeans;

import com.weipan.smk1.bean.GvBeansDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gvBeansDaoConfig;

    private final GvBeansDao gvBeansDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gvBeansDaoConfig = daoConfigMap.get(GvBeansDao.class).clone();
        gvBeansDaoConfig.initIdentityScope(type);

        gvBeansDao = new GvBeansDao(gvBeansDaoConfig, this);

        registerDao(GvBeans.class, gvBeansDao);
    }
    
    public void clear() {
        gvBeansDaoConfig.clearIdentityScope();
    }

    public GvBeansDao getGvBeansDao() {
        return gvBeansDao;
    }

}
